# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc

from pactus.proto import utils_pb2 as pactus_dot_proto_dot_utils__pb2

GRPC_GENERATED_VERSION = "1.66.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in pactus/proto/utils_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class UtilsStub(object):
    """Utils service defines RPC methods for utility functions such as message
    signing and verification.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SignMessageWithPrivateKey = channel.unary_unary(
            "/pactus.Utils/SignMessageWithPrivateKey",
            request_serializer=pactus_dot_proto_dot_utils__pb2.SignMessageWithPrivateKeyRequest.SerializeToString,
            response_deserializer=pactus_dot_proto_dot_utils__pb2.SignMessageWithPrivateKeyResponse.FromString,
            _registered_method=True,
        )
        self.VerifyMessage = channel.unary_unary(
            "/pactus.Utils/VerifyMessage",
            request_serializer=pactus_dot_proto_dot_utils__pb2.VerifyMessageRequest.SerializeToString,
            response_deserializer=pactus_dot_proto_dot_utils__pb2.VerifyMessageResponse.FromString,
            _registered_method=True,
        )


class UtilsServicer(object):
    """Utils service defines RPC methods for utility functions such as message
    signing and verification.
    """

    def SignMessageWithPrivateKey(self, request, context):
        """SignMessageWithPrivateKey sign message with provided private key."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def VerifyMessage(self, request, context):
        """VerifyMessage verify signature with public key and message"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_UtilsServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SignMessageWithPrivateKey": grpc.unary_unary_rpc_method_handler(
            servicer.SignMessageWithPrivateKey,
            request_deserializer=pactus_dot_proto_dot_utils__pb2.SignMessageWithPrivateKeyRequest.FromString,
            response_serializer=pactus_dot_proto_dot_utils__pb2.SignMessageWithPrivateKeyResponse.SerializeToString,
        ),
        "VerifyMessage": grpc.unary_unary_rpc_method_handler(
            servicer.VerifyMessage,
            request_deserializer=pactus_dot_proto_dot_utils__pb2.VerifyMessageRequest.FromString,
            response_serializer=pactus_dot_proto_dot_utils__pb2.VerifyMessageResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "pactus.Utils", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("pactus.Utils", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Utils(object):
    """Utils service defines RPC methods for utility functions such as message
    signing and verification.
    """

    @staticmethod
    def SignMessageWithPrivateKey(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pactus.Utils/SignMessageWithPrivateKey",
            pactus_dot_proto_dot_utils__pb2.SignMessageWithPrivateKeyRequest.SerializeToString,
            pactus_dot_proto_dot_utils__pb2.SignMessageWithPrivateKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def VerifyMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pactus.Utils/VerifyMessage",
            pactus_dot_proto_dot_utils__pb2.VerifyMessageRequest.SerializeToString,
            pactus_dot_proto_dot_utils__pb2.VerifyMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
